
package ventanas.paneles;
import java.awt.*;

import java.awt.event.*;
import javax.swing.*;
import ventanas.paneles.PPrincipal;
import ventanas.VentanaPrincipal;





public class Pidioma extends JPanel {
 
    private static final long serialVersionUID = 1L;
    GridBagConstraints gridBagConstraints = new GridBagConstraints();

    // Variables declaration - do not modify//GEN-BEGIN:variables
      private JButton ButtonCastellano;
      private JButton ButtonGallego;
      private JScrollPane jScrollPane1;
      private JScrollPane jScrollPane2;
      private JScrollPane jScrollPane3;
      private JScrollPane jScrollPane4;
      private JScrollPane jScrollPane5;
      private JScrollPane jScrollPane6;
      private JScrollPane jScrollPane7;
      private JScrollPane jScrollPane8;
      private JTextArea textoGalTitulo;
      private JTextArea textoEspTitulo;
      private JTextArea leyGalPParrafo;
      private JTextArea leyGalSParrafo;
      private JTextArea leyEspPParrafo;
      private JTextArea leyEspSParrafo;
      private JTextArea leyGalTParrafo;
      private JTextArea leyEspTParrafo;
      private JComponent pPrincipal;
      private JComponent pIdioma;
     

   
    public Pidioma() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        ImageIcon img = new ImageIcon("src/main/java/imagenes/fondo.jpg");
        g.drawImage(img.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
    }
    private void initComponents() {
        GridBagConstraints gridBagConstraints = new GridBagConstraints();

        jScrollPane1 = new JScrollPane();
        textoGalTitulo = new JTextArea();
        jScrollPane2 = new JScrollPane();
        textoEspTitulo = new JTextArea();
        jScrollPane3 = new JScrollPane();
        leyGalPParrafo = new JTextArea();
        jScrollPane4 = new JScrollPane();
        leyGalSParrafo = new JTextArea();
        jScrollPane5 = new JScrollPane();
        leyEspPParrafo = new JTextArea();
        jScrollPane6 = new JScrollPane();
        leyEspSParrafo = new JTextArea();
        jScrollPane7 = new JScrollPane();
        leyGalTParrafo = new JTextArea();
        jScrollPane8 = new JScrollPane();
        leyEspTParrafo = new JTextArea();
        ButtonGallego = new JButton();
        ButtonCastellano = new JButton();


        setLayout(new GridBagLayout());

        ;
        textoGalTitulo.setColumns(20);
        textoGalTitulo.setFont(new Font("Roboto", 0, 23)); // NOI18N
        textoGalTitulo.setRows(5);
        textoGalTitulo.setText("           DECLARACIÓN RESPONSABLE /\n SOLICITUDE DE LICENZA ESPECTÁCULOS \n                                  PÚBLICOS");
        textoGalTitulo.setEditable(false);
        textoGalTitulo.setOpaque(false);
        textoGalTitulo.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(textoGalTitulo);
        jScrollPane1.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setOpaque(false);
      
       

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 458;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.20;
        gridBagConstraints.insets = new Insets(20, 21, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        
        textoEspTitulo.setColumns(20);
        textoEspTitulo.setFont(new Font("Roboto", 0, 23)); // NOI18N
        textoEspTitulo.setRows(5);
        textoEspTitulo.setText("            DECLARACIÓN RESPONSABLE / \n  SOLICITUD DE LICENCIA ESPECTÁCULOS\n                                PÚBLICOS");
        textoEspTitulo.setEditable(false);
        textoEspTitulo.setOpaque(false);
        jScrollPane2.setViewportView(textoEspTitulo);
        jScrollPane2.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 434;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.2;
        gridBagConstraints.insets = new Insets(20, 26, 0, 0);
        add(jScrollPane2, gridBagConstraints);

        
        leyGalPParrafo.setColumns(20);
        leyGalPParrafo.setFont(new Font("Roboto", 0, 13)); // NOI18N
        leyGalPParrafo.setRows(5);
        leyGalPParrafo.setText("        Decreto 144/2016, do 22 de septembro, polo que se \n  aproba o Regulamento único  de  regulación integrada de \n  actividades  económicas  e  apertura  de establecementos\n\n\n");
        leyGalPParrafo.setEditable(false);
        leyGalPParrafo.setOpaque(false);
        jScrollPane3.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane3.setOpaque(false);
        jScrollPane3.setBorder(null);
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.setViewportView(leyGalPParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-60, 74, 0, 0);
        add(jScrollPane3, gridBagConstraints);

      
        leyGalSParrafo.setColumns(20);
        leyGalSParrafo.setFont(new Font("Roboto", 0, 14)); // NOI18N
        leyGalSParrafo.setRows(5);
        leyGalSParrafo.setText(" Lei  10/2017,  do  27  de  decembro,  de  espectáculos \n      públicos  e actividades recreativas de Galicia.\n");
        leyGalSParrafo.setEditable(false);
        leyGalSParrafo.setOpaque(false);
        jScrollPane4.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane4.setOpaque(false);
        jScrollPane4.setBorder(null);
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.setViewportView(leyGalSParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-70, 74, 0, 0);
        add(jScrollPane4, gridBagConstraints);

        leyEspPParrafo.setColumns(20);
        leyEspPParrafo.setFont(new Font("Roboto", 0, 13)); // NOI18N
        leyEspPParrafo.setRows(5);
        leyEspPParrafo.setText("    Decreto 144/2016, del 22 de septiembre, por el que se\n  aprueba el Reglamento único  de  regulación integrada\n de  actividades  económicas  y  apertura  de establecimientos.");
        leyEspPParrafo.setEditable(false);
        leyEspPParrafo.setOpaque(false);
        jScrollPane5.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane5.setOpaque(false);
        jScrollPane5.setBorder(null);
        jScrollPane5.getViewport().setOpaque(false);
        jScrollPane5.setViewportView(leyEspPParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-60, 69, 0, 0);
        add(jScrollPane5, gridBagConstraints);

        leyEspSParrafo.setColumns(20);
        leyEspSParrafo.setFont(new Font("Roboto", 0, 14)); // NOI18N
        leyEspSParrafo.setRows(5);
        leyEspSParrafo.setText("  Ley  10/2017,  del  27  de  diciembre,  de  espectáculos\n       públicos  y actividades  recreativas de Galicia.");
        leyEspSParrafo.setEditable(false);
        leyEspSParrafo.setOpaque(false);
        jScrollPane6.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane6.setOpaque(false);
        jScrollPane6.setBorder(null);
        jScrollPane6.getViewport().setOpaque(false);
        jScrollPane6.setViewportView(leyEspSParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-70, 69, 0, 0);
        add(jScrollPane6, gridBagConstraints);

        leyGalTParrafo.setColumns(20);
        leyGalTParrafo.setFont(new Font("Roboto", 0, 14)); // NOI18N
        leyGalTParrafo.setRows(5);
        leyGalTParrafo.setText(" Decreto  124/2019,  do  5  de  setembro,  polo  que  se  aproba\n  o  Catálogo  de espectáculos  públicos,  actividades  \nrecreativas  e  establecimeintos  aiertos  ao público  da \n Comunidade  Autónoma de  Galicia  e se  establecen  \ndeterminadas  disposicións xerais de aplicación na materia.\n");
        leyGalTParrafo.setEditable(false);
        leyGalTParrafo.setOpaque(false);
        jScrollPane7.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane7.setOpaque(false);
        jScrollPane7.setBorder(null);
        jScrollPane7.getViewport().setOpaque(false);
        jScrollPane7.setViewportView(leyGalTParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 250;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-100, 74, 0, 0);
        add(jScrollPane7, gridBagConstraints);

        leyEspTParrafo.setColumns(20);
        leyEspTParrafo.setFont(new Font("Roboto Condensed", 0, 14)); // NOI18N
        leyEspTParrafo.setRows(5);
        leyEspTParrafo.setText(" Decreto  124/2019,  del  5  de  septiembre,  por el  que  se  aprueba  \n el  Catálogo  de espectáculos  públicos,  actividades  recreativas \n y  establecimeintos  abiertos  al público  de la  Comunidad  \n Autónoma  de  Galicia  y se  establecen  determinadas \n disposiciones generales de aplicación en la materia.");
        leyEspTParrafo.setEditable(false);
        leyEspTParrafo.setOpaque(false);
        jScrollPane8.getViewport().setBackground(new Color(0, 0, 0,0));
        jScrollPane8.setOpaque(false);
        jScrollPane8.setBorder(null);
        jScrollPane8.getViewport().setOpaque(false);
        jScrollPane8.setViewportView(leyEspTParrafo);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 250;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(-100, 69, 0, 0);
        add(jScrollPane8, gridBagConstraints);

        ButtonGallego.setFont(new Font("Roboto Condensed", 0, 24)); // NOI18N
        ButtonGallego.setText("Galego");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.insets = new Insets(-260, 203, 71, 0);
        add(ButtonGallego, gridBagConstraints);

        ButtonCastellano.setFont(new Font("Roboto Condensed", 0, 24)); // NOI18N
        ButtonCastellano.setText("Castellano");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.insets = new Insets(-260, 190, 71, 0);
        add(ButtonCastellano, gridBagConstraints);

        ActionListener click = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
               
               
                pPrincipal.setVisible(true);
               
                pIdioma.setVisible(false);
                
                
            }
         };
         ButtonCastellano.addActionListener(click);
        
    }

}
