
package ventanas.paneles;
import java.awt.*;
import javax.swing.*;




public class Pidioma extends JPanel {
 
    private static final long serialVersionUID = 1L;

    // Variables declaration - do not modify//GEN-BEGIN:variables
      private JButton ButtonCastellano;
      private JButton ButtonGallego;
      private JScrollPane jScrollPane1;
      private JScrollPane jScrollPane2;
      private JScrollPane jScrollPane3;
      private JScrollPane jScrollPane4;
      private JScrollPane jScrollPane5;
      private JScrollPane jScrollPane6;
      private JScrollPane jScrollPane7;
      private JScrollPane jScrollPane8;
      private JTextArea jTextArea1;
      private JTextArea jTextArea2;
      private JTextArea jTextArea3;
      private JTextArea jTextArea4;
      private JTextArea jTextArea5;
      private JTextArea jTextArea6;
      private JTextArea jTextArea7;
      private JTextArea jTextArea8;
   
    public Pidioma() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        ButtonGallego = new javax.swing.JButton();
        ButtonCastellano = new javax.swing.JButton();

        setLayout(new GridBagLayout());

        jTextArea1.setBackground(new Color(254, 254, 254));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new Font("Roboto", 0, 23)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("           DECLARACIÓN RESPONSABLE /\n SOLICITUDE DE LICENZA ESPECTÁCULOS \n                                  PÚBLICOS");
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 458;
        gridBagConstraints.ipady = 156;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(30, 21, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new Font("Roboto", 0, 23)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("            DECLARACIÓN RESPONSABLE / \n  SOLICITUD DE LICENCIA ESPECTÁCULOS\n                                PÚBLICOS");
        jScrollPane2.setViewportView(jTextArea2);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 434;
        gridBagConstraints.ipady = 156;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(30, 26, 0, 0);
        add(jScrollPane2, gridBagConstraints);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new Font("Roboto", 0, 13)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("        Decreto 144/2016, do 22 de septembro, polo que se \n  aproba o Regulamento único  de  regulación integrada de \n  actividades  económicas  e  apertura  de establecementos\n\n\n");
        jScrollPane3.setViewportView(jTextArea3);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 74, 0, 0);
        add(jScrollPane3, gridBagConstraints);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new Font("Roboto", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText(" Lei  10/2017,  do  27  de  decembro,  de  espectáculos \n      públicos  e actividades recreativas de Galicia.\n");
        jScrollPane4.setViewportView(jTextArea4);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 74, 0, 0);
        add(jScrollPane4, gridBagConstraints);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new Font("Roboto", 0, 13)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("    Decreto 144/2016, del 22 de septiembre, por el que se\n  aprueba el Reglamento único  de  regulación integrada\n de  actividades  económicas  y  apertura  de establecimientos.");
        jScrollPane5.setViewportView(jTextArea5);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 69, 0, 0);
        add(jScrollPane5, gridBagConstraints);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new Font("Roboto", 0, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("  Ley  10/2017,  del  27  de  diciembre,  de  espectáculos\n       públicos  y actividades  recreativas de Galicia.");
        jScrollPane6.setViewportView(jTextArea6);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 78;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 69, 0, 0);
        add(jScrollPane6, gridBagConstraints);

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new Font("Roboto", 0, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText(" Decreto  124/2019,  do  5  de  setembro,  polo  que  se  aproba\n  o  Catálogo  de espectáculos  públicos,  actividades  \nrecreativas  e  establecimeintos  aiertos  ao público  da \n Comunidade  Autónoma de  Galicia  e se  establecen  \ndeterminadas  disposicións xerais de aplicación na materia.\n");
        jScrollPane7.setViewportView(jTextArea7);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 405;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 74, 0, 0);
        add(jScrollPane7, gridBagConstraints);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new Font("Roboto Condensed", 0, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText(" Decreto  124/2019,  del  5  de  septiembre,  por el  que  se  aprueba  \n el  Catálogo  de espectáculos  públicos,  actividades  recreativas \n y  establecimeintos  abiertos  al público  de la  Comunidad  \n Autónoma  de  Galicia  y se  establecen  determinadas \n disposiciones generales de aplicación en la materia.");
        jScrollPane8.setViewportView(jTextArea8);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 403;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 69, 0, 0);
        add(jScrollPane8, gridBagConstraints);

        ButtonGallego.setFont(new Font("Roboto Condensed", 0, 24)); // NOI18N
        ButtonGallego.setText("Galego");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(31, 233, 71, 0);
        add(ButtonGallego, gridBagConstraints);

        ButtonCastellano.setFont(new Font("Roboto Condensed", 0, 24)); // NOI18N
        ButtonCastellano.setText("Castellano");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(31, 221, 71, 0);
        add(ButtonCastellano, gridBagConstraints);

    }


  
}
