/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas.paneles;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author Persona
 */
public class PPersonaJuridicoEccom extends javax.swing.JPanel implements ChangeListener{

    /**
     * Creates new form PPersonaJuridicoEccom
     */
    public PPersonaJuridicoEccom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoBotones = new javax.swing.ButtonGroup();
        textoOrganizador = new javax.swing.JLabel();
        botonPersonaFisica = new javax.swing.JRadioButton();
        botonPersonaJuridica = new javax.swing.JRadioButton();
        botonECCOM = new javax.swing.JRadioButton();
        botonCancelar = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        textoNumeroOrganizadores = new javax.swing.JLabel();
        textoNIF = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JLabel();
        textoPoblacion = new javax.swing.JLabel();
        textoProvincia = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JLabel();
        textoMobil = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoEpigrafe = new javax.swing.JLabel();
        textoSeguro = new javax.swing.JLabel();
        textoCobertura = new javax.swing.JLabel();
        textoContenedorNumeroOrganizadores = new javax.swing.JTextField();
        textoContenedorNIF = new javax.swing.JTextField();
        textoContenedorApellidos = new javax.swing.JTextField();
        textoContenedorNombre = new javax.swing.JTextField();
        textoContenedorDireccion = new javax.swing.JTextField();
        textoContenedorPoblacion = new javax.swing.JTextField();
        textoContenedorProvincia = new javax.swing.JTextField();
        textoContenedorTelefono = new javax.swing.JTextField();
        textoContenedorMobil = new javax.swing.JTextField();
        textoContenedorEmail = new javax.swing.JTextField();
        textoContenedorEpigrafe = new javax.swing.JTextField();
        textoContenedorSeguro = new javax.swing.JTextField();
        textoContenedorCobertura = new javax.swing.JTextField();
        textoContenedorCoberturaEccom = new javax.swing.JTextField();
        textoErrorNumeroOrganizadores = new javax.swing.JLabel();
        textoErrorNIF = new javax.swing.JLabel();
        textoErrorApellidos = new javax.swing.JLabel();
        textoErrorNombre = new javax.swing.JLabel();
        textoErrorDireccion = new javax.swing.JLabel();
        textoErrorPoblacion = new javax.swing.JLabel();
        textoErrorProvincia = new javax.swing.JLabel();
        textoErrorTelefono = new javax.swing.JLabel();
        textoErrorMobil = new javax.swing.JLabel();
        textoErrorEmail = new javax.swing.JLabel();
        textoErrorEpigrafe = new javax.swing.JLabel();
        textoErrorSeguro = new javax.swing.JLabel();
        textoErrorCobertura = new javax.swing.JLabel();
        textoErrorCoberturaEccom = new javax.swing.JLabel();
        textoRegistro = new javax.swing.JLabel();
        textoCIF = new javax.swing.JLabel();
        textoRazonSocial = new javax.swing.JLabel();
        textoDireccionJuEccom = new javax.swing.JLabel();
        textoPoblacionJuEccom = new javax.swing.JLabel();
        textoProvinciaJuEccom = new javax.swing.JLabel();
        textoTelefonoJuEccom = new javax.swing.JLabel();
        textoMobilJuEccom = new javax.swing.JLabel();
        textoEmailJuEccom = new javax.swing.JLabel();
        textoRepresentante = new javax.swing.JLabel();
        textoHabilitacion = new javax.swing.JLabel();
        textoAlcanceCertificacion = new javax.swing.JLabel();
        textoSeguroEccom = new javax.swing.JLabel();
        textoCoberturaEccom = new javax.swing.JLabel();

        grupoBotones.add(botonPersonaFisica);
        grupoBotones.add(botonPersonaJuridica);
        grupoBotones.add(botonECCOM);

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0};
        layout.rowHeights = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0};
        setLayout(layout);

        textoOrganizador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textoOrganizador.setText("ORGANIZADOR");
        textoOrganizador.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(textoOrganizador, gridBagConstraints);

        botonPersonaFisica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonPersonaFisica.setText("Persona Física");
        botonPersonaFisica.setSelected(true);
        botonPersonaFisica.setPreferredSize(new java.awt.Dimension(232, 23));
        botonPersonaFisica.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(botonPersonaFisica, gridBagConstraints);

        botonPersonaJuridica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonPersonaJuridica.setText("Persona Jurídica");
        botonPersonaJuridica.setPreferredSize(new java.awt.Dimension(232, 23));
        botonPersonaJuridica.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(botonPersonaJuridica, gridBagConstraints);

        botonECCOM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonECCOM.setText("ECCOM");
        botonECCOM.setPreferredSize(new java.awt.Dimension(232, 23));
        botonECCOM.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(botonECCOM, gridBagConstraints);

        botonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        botonCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(botonCancelar, gridBagConstraints);

        botonSiguiente.setBackground(new java.awt.Color(51, 153, 255));
        botonSiguiente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonSiguiente.setText("Siguiente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(botonSiguiente, gridBagConstraints);

        textoNumeroOrganizadores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoNumeroOrganizadores.setText("Nº de organizadores/as");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoNumeroOrganizadores, gridBagConstraints);

        textoNIF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoNIF.setText("NIF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoNIF, gridBagConstraints);

        textoApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoApellidos.setText("Apellidos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoApellidos, gridBagConstraints);

        textoNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoNombre, gridBagConstraints);

        textoDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoDireccion.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoDireccion, gridBagConstraints);

        textoPoblacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoPoblacion.setText("Población");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoPoblacion, gridBagConstraints);

        textoProvincia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoProvincia.setText("Provincia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoProvincia, gridBagConstraints);

        textoTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoTelefono.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoTelefono, gridBagConstraints);

        textoMobil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoMobil.setText("Móbil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoMobil, gridBagConstraints);

        textoEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoEmail.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoEmail, gridBagConstraints);

        textoEpigrafe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoEpigrafe.setText("Epígrafe IAE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoEpigrafe, gridBagConstraints);

        textoSeguro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoSeguro.setText("Póliza de Seguro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoSeguro, gridBagConstraints);

        textoCobertura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoCobertura.setText("Cobertura (€)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoCobertura, gridBagConstraints);

        textoContenedorNumeroOrganizadores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorNumeroOrganizadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorNumeroOrganizadores.setMinimumSize(new java.awt.Dimension(50, 20));
        textoContenedorNumeroOrganizadores.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorNumeroOrganizadores, gridBagConstraints);

        textoContenedorNIF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorNIF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorNIF.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorNIF.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorNIF, gridBagConstraints);

        textoContenedorApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorApellidos.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorApellidos.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorApellidos, gridBagConstraints);

        textoContenedorNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorNombre.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorNombre.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorNombre, gridBagConstraints);

        textoContenedorDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorDireccion.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorDireccion.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorDireccion, gridBagConstraints);

        textoContenedorPoblacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorPoblacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorPoblacion.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorPoblacion.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorPoblacion, gridBagConstraints);

        textoContenedorProvincia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorProvincia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorProvincia.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorProvincia.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorProvincia, gridBagConstraints);

        textoContenedorTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorTelefono.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorTelefono.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorTelefono, gridBagConstraints);

        textoContenedorMobil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorMobil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorMobil.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorMobil.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorMobil, gridBagConstraints);

        textoContenedorEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorEmail.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorEmail.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorEmail, gridBagConstraints);

        textoContenedorEpigrafe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorEpigrafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorEpigrafe.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorEpigrafe.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorEpigrafe, gridBagConstraints);

        textoContenedorSeguro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorSeguro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorSeguro.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorSeguro.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorSeguro, gridBagConstraints);

        textoContenedorCobertura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorCobertura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorCobertura.setMinimumSize(new java.awt.Dimension(130, 20));
        textoContenedorCobertura.setPreferredSize(new java.awt.Dimension(130, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorCobertura, gridBagConstraints);

        textoContenedorCoberturaEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoContenedorCoberturaEccom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoContenedorCoberturaEccom.setPreferredSize(new java.awt.Dimension(130, 20));
        textoContenedorCoberturaEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoContenedorCoberturaEccom, gridBagConstraints);

        textoErrorNumeroOrganizadores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorNumeroOrganizadores.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorNumeroOrganizadores.setText("Debe introducir un número");
        textoErrorNumeroOrganizadores.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorNumeroOrganizadores.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        add(textoErrorNumeroOrganizadores, gridBagConstraints);

        textoErrorNIF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorNIF.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorNIF.setText("El NIF de contener 9 dígitos ");
        textoErrorNIF.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorNIF.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        add(textoErrorNIF, gridBagConstraints);

        textoErrorApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorApellidos.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorApellidos.setText("Debe ingresar un apellido válido");
        textoErrorApellidos.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorApellidos.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        add(textoErrorApellidos, gridBagConstraints);

        textoErrorNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorNombre.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorNombre.setText("Debe ingresar un nombre válido");
        textoErrorNombre.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorNombre.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        add(textoErrorNombre, gridBagConstraints);

        textoErrorDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorDireccion.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorDireccion.setText("Debe ingresar una dirección válida");
        textoErrorDireccion.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorDireccion.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        add(textoErrorDireccion, gridBagConstraints);

        textoErrorPoblacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorPoblacion.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorPoblacion.setText("Debe ingresar una población válida");
        textoErrorPoblacion.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorPoblacion.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        add(textoErrorPoblacion, gridBagConstraints);

        textoErrorProvincia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorProvincia.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorProvincia.setText("Debe ingresar una provincia válida");
        textoErrorProvincia.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorProvincia.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        add(textoErrorProvincia, gridBagConstraints);

        textoErrorTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorTelefono.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorTelefono.setText("Debe ingresar un teléfono válido");
        textoErrorTelefono.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorTelefono.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        add(textoErrorTelefono, gridBagConstraints);

        textoErrorMobil.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorMobil.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorMobil.setText("jLabel2");
        textoErrorMobil.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorMobil.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        add(textoErrorMobil, gridBagConstraints);

        textoErrorEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorEmail.setText("Debe ingresar un E-mail válido");
        textoErrorEmail.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorEmail.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        add(textoErrorEmail, gridBagConstraints);

        textoErrorEpigrafe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorEpigrafe.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorEpigrafe.setText("Debe ingresar un epígrafe IAE válido");
        textoErrorEpigrafe.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorEpigrafe.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        add(textoErrorEpigrafe, gridBagConstraints);

        textoErrorSeguro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorSeguro.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorSeguro.setText("Debe ingresar una póliza de seguro válida");
        textoErrorSeguro.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoErrorSeguro, gridBagConstraints);

        textoErrorCobertura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorCobertura.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorCobertura.setText("Debe ingresar una cobertura válida");
        textoErrorCobertura.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorCobertura.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 28;
        add(textoErrorCobertura, gridBagConstraints);

        textoErrorCoberturaEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoErrorCoberturaEccom.setForeground(new java.awt.Color(255, 51, 51));
        textoErrorCoberturaEccom.setText("Debe ingresar una cobertura válida");
        textoErrorCoberturaEccom.setPreferredSize(new java.awt.Dimension(232, 14));
        textoErrorCoberturaEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 30;
        add(textoErrorCoberturaEccom, gridBagConstraints);

        textoRegistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoRegistro.setText("Nº Registro");
        textoRegistro.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoRegistro, gridBagConstraints);

        textoCIF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoCIF.setText("CIF");
        textoCIF.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoCIF, gridBagConstraints);

        textoRazonSocial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoRazonSocial.setText("Razón Social");
        textoRazonSocial.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoRazonSocial, gridBagConstraints);

        textoDireccionJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoDireccionJuEccom.setText("Dirección");
        textoDireccionJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoDireccionJuEccom, gridBagConstraints);

        textoPoblacionJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoPoblacionJuEccom.setText("Población");
        textoPoblacionJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoPoblacionJuEccom, gridBagConstraints);

        textoProvinciaJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoProvinciaJuEccom.setText("Provincia");
        textoProvinciaJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoProvinciaJuEccom, gridBagConstraints);

        textoTelefonoJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoTelefonoJuEccom.setText("Teléfono");
        textoTelefonoJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoTelefonoJuEccom, gridBagConstraints);

        textoMobilJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoMobilJuEccom.setText("Móbil");
        textoMobilJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoMobilJuEccom, gridBagConstraints);

        textoEmailJuEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoEmailJuEccom.setText("E-mail");
        textoEmailJuEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoEmailJuEccom, gridBagConstraints);

        textoRepresentante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoRepresentante.setText("Representante");
        textoRepresentante.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoRepresentante, gridBagConstraints);

        textoHabilitacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoHabilitacion.setText("Habilitación");
        textoHabilitacion.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoHabilitacion, gridBagConstraints);

        textoAlcanceCertificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoAlcanceCertificacion.setText("Alcance de certificación");
        textoAlcanceCertificacion.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoAlcanceCertificacion, gridBagConstraints);

        textoSeguroEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoSeguroEccom.setText("Póliza de Seguro");
        textoSeguroEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoSeguroEccom, gridBagConstraints);

        textoCoberturaEccom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textoCoberturaEccom.setText("Cobertura (€)");
        textoCoberturaEccom.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(textoCoberturaEccom, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    
    public void stateChanged(ChangeEvent e) {
        if (botonPersonaFisica.isSelected()) {
            textoNumeroOrganizadores.setVisible(true);
            textoNIF.setVisible(true);
            textoApellidos.setVisible(true);
            textoNombre.setVisible(true);
            textoDireccion.setVisible(true);
            textoPoblacion.setVisible(true);
            textoProvincia.setVisible(true);
            textoTelefono.setVisible(true);
            textoMobil.setVisible(true);
            textoEmail.setVisible(true);
            textoEpigrafe.setVisible(true);
            textoSeguro.setVisible(true);
            textoCobertura.setVisible(true);
            
            textoRegistro.setVisible(false);
            textoCIF.setVisible(false);
            textoRazonSocial.setVisible(false);
            textoDireccionJuEccom.setVisible(false);
            textoPoblacionJuEccom.setVisible(false);
            textoProvinciaJuEccom.setVisible(false);
            textoTelefonoJuEccom.setVisible(false);
            textoMobilJuEccom.setVisible(false);
            textoEmailJuEccom.setVisible(false);
            textoRepresentante.setVisible(false);
            textoCoberturaEccom.setVisible(false);
            textoContenedorCoberturaEccom.setVisible(false);
            textoHabilitacion.setVisible(false);
            textoAlcanceCertificacion.setVisible(false);
            textoSeguroEccom.setVisible(false);
        }
        else if (botonPersonaJuridica.isSelected()) {
            textoNIF.setVisible(false);
            textoApellidos.setVisible(false);
            textoNombre.setVisible(false);
            textoDireccion.setVisible(false);
            textoPoblacion.setVisible(false);
            textoProvincia.setVisible(false);
            textoTelefono.setVisible(false);
            textoMobil.setVisible(false);
            textoEmail.setVisible(false);
            textoCoberturaEccom.setVisible(false);
            textoContenedorCoberturaEccom.setVisible(false);
            textoHabilitacion.setVisible(false);
            textoAlcanceCertificacion.setVisible(false);
            textoSeguroEccom.setVisible(false);
            textoRegistro.setVisible(false);            
           
            textoNumeroOrganizadores.setVisible(true);
            textoCIF.setVisible(true);
            textoRazonSocial.setVisible(true);
            textoDireccionJuEccom.setVisible(true);
            textoPoblacionJuEccom.setVisible(true);
            textoProvinciaJuEccom.setVisible(true);
            textoTelefonoJuEccom.setVisible(true);
            textoMobilJuEccom.setVisible(true);
            textoEmailJuEccom.setVisible(true);
            textoRepresentante.setVisible(true);
            textoEpigrafe.setVisible(true);
            textoSeguro.setVisible(true);
            textoCobertura.setVisible(true);
        }
        else if (botonECCOM.isSelected()){
            textoNumeroOrganizadores.setVisible(false);            
            textoNIF.setVisible(false);
            textoApellidos.setVisible(false);
            textoNombre.setVisible(false);
            textoDireccion.setVisible(false);
            textoPoblacion.setVisible(false);
            textoProvincia.setVisible(false);
            textoTelefono.setVisible(false);
            textoMobil.setVisible(false);
            textoEmail.setVisible(false);
            textoEpigrafe.setVisible(false);
            textoSeguro.setVisible(false);
            textoCobertura.setVisible(false);
            
            textoRegistro.setVisible(true);            
            textoCIF.setVisible(true);
            textoRazonSocial.setVisible(true);
            textoDireccionJuEccom.setVisible(true);
            textoPoblacionJuEccom.setVisible(true);
            textoProvinciaJuEccom.setVisible(true);
            textoTelefonoJuEccom.setVisible(true);
            textoMobilJuEccom.setVisible(true);
            textoEmailJuEccom.setVisible(true);
            textoRepresentante.setVisible(true);
            textoHabilitacion.setVisible(true);
            textoAlcanceCertificacion.setVisible(true);
            textoSeguroEccom.setVisible(true);
            textoCoberturaEccom.setVisible(true);
            textoContenedorCoberturaEccom.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JRadioButton botonECCOM;
    private javax.swing.JRadioButton botonPersonaFisica;
    private javax.swing.JRadioButton botonPersonaJuridica;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel textoAlcanceCertificacion;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoCIF;
    private javax.swing.JLabel textoCobertura;
    private javax.swing.JLabel textoCoberturaEccom;
    private javax.swing.JTextField textoContenedorApellidos;
    private javax.swing.JTextField textoContenedorCobertura;
    private javax.swing.JTextField textoContenedorCoberturaEccom;
    private javax.swing.JTextField textoContenedorDireccion;
    private javax.swing.JTextField textoContenedorEmail;
    private javax.swing.JTextField textoContenedorEpigrafe;
    private javax.swing.JTextField textoContenedorMobil;
    private javax.swing.JTextField textoContenedorNIF;
    private javax.swing.JTextField textoContenedorNombre;
    private javax.swing.JTextField textoContenedorNumeroOrganizadores;
    private javax.swing.JTextField textoContenedorPoblacion;
    private javax.swing.JTextField textoContenedorProvincia;
    private javax.swing.JTextField textoContenedorSeguro;
    private javax.swing.JTextField textoContenedorTelefono;
    private javax.swing.JLabel textoDireccion;
    private javax.swing.JLabel textoDireccionJuEccom;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoEmailJuEccom;
    private javax.swing.JLabel textoEpigrafe;
    private javax.swing.JLabel textoErrorApellidos;
    private javax.swing.JLabel textoErrorCobertura;
    private javax.swing.JLabel textoErrorCoberturaEccom;
    private javax.swing.JLabel textoErrorDireccion;
    private javax.swing.JLabel textoErrorEmail;
    private javax.swing.JLabel textoErrorEpigrafe;
    private javax.swing.JLabel textoErrorMobil;
    private javax.swing.JLabel textoErrorNIF;
    private javax.swing.JLabel textoErrorNombre;
    private javax.swing.JLabel textoErrorNumeroOrganizadores;
    private javax.swing.JLabel textoErrorPoblacion;
    private javax.swing.JLabel textoErrorProvincia;
    private javax.swing.JLabel textoErrorSeguro;
    private javax.swing.JLabel textoErrorTelefono;
    private javax.swing.JLabel textoHabilitacion;
    private javax.swing.JLabel textoMobil;
    private javax.swing.JLabel textoMobilJuEccom;
    private javax.swing.JLabel textoNIF;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoNumeroOrganizadores;
    private javax.swing.JLabel textoOrganizador;
    private javax.swing.JLabel textoPoblacion;
    private javax.swing.JLabel textoPoblacionJuEccom;
    private javax.swing.JLabel textoProvincia;
    private javax.swing.JLabel textoProvinciaJuEccom;
    private javax.swing.JLabel textoRazonSocial;
    private javax.swing.JLabel textoRegistro;
    private javax.swing.JLabel textoRepresentante;
    private javax.swing.JLabel textoSeguro;
    private javax.swing.JLabel textoSeguroEccom;
    private javax.swing.JLabel textoTelefono;
    private javax.swing.JLabel textoTelefonoJuEccom;
    // End of variables declaration//GEN-END:variables
}
